sudo: false

language: python

matrix:
  include:
  - python: 3.6
    env: TOXENV=py

install:
- pip install tox

script:
- tox

before_cache:
- rm -rf $HOME/.cache/pip/log

cache:
  directories:
  - $HOME/.cache/pip
